org: "Carnegie Mellon University"
suborg: "Software and Societal Systems"
office: "TCS Hall 224"
description: >-
domain: "icmccorm.com"
url: "https://icmccorm.com"
baseurl: ""
social_tag: icmccorm
email: icmccorm@cs.cmu.edu
orcid_id: "0000-0001-6349-3402"
source: ./
sass:
    sass_dir: assets/css/_sass
    style: compressed
favicon:
  path: assets/img
collections:
  - publications